# Dockerfile for the Celery service
FROM python:3.10-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["celery", "worker", "-A", "myproject", "-l", "info"]

